### ISSUE TITLE
Readme should show wildcard usage too

### ISSUE THREAD

**Issue by paul-hammant** [raviqqe/linkcheck#3]
The ascii-cinema vid shows it, but it not apparent in the README

**Comment by raviqqe** [comment]
The wildcard usage (`liche **/*.md`) is not listed in README because it's not a feature of `liche` but zsh. Recursive wildcard patterns are not available on other shell like Bourne shell and bash. But, non-recursive ones are available on most shells.

```sh
> liche *.md
> liche *.html
```

Do you think we should list them in the usage?

**Comment by paul-hammant** [comment]
I was thinking of a `-r` option, but it's your choice

**Comment by raviqqe** [comment]
Recursive option is added.

**Comment by paul-hammant** [comment]
Yay, great work Sir!
