### ISSUE TITLE
Support crawling a website via HTTP

### ISSUE THREAD

**Issue by fd0** [raviqqe/linkcheck#6]
Hi,

thanks for publishing liche! Would you consider adding support for crawling a website via HTTP? I'd like to check the website for [restic](https://github.com/restic/restic) (a backup program written in Go) using something else than `linkchecker`. We have some rewriting magic going on via the webserver on https://restic.net, so checking the local files does not work completely.

I'd like to be able to do this (with liche):

```
$ linkchecker --check-extern --no-robots http://localhost:4000
```

Where on `localhost` on port 4000 I have an instance of Jekyll running, serving the files.

What's your take on that? I'd be willing to submit a PR if you're interested.

**Comment by raviqqe** [comment]
Sounds nice to me while I prefer to make it a fork as `liche` was originally meant to check local simple Markdown files like README.md. I also want to know whether you have written some patch already otherwise I can work on it.

BTW, what is `--no-robots` flag? If you are talking about something like `robots.txt`, I guess we can just extract URLs from root websites and then traverse the entire pages recursively.

**Comment by fd0** [comment]
By default, `linkchecker` won't check URLs pointing to GitHub, because they have forbidden all unknown robots via their `robots.txt`. So `--no-robots` is needed to tell `linkchecker` to ignore this.

I did not start any work yet. It would be most awesome if you could add that feature, thank you very much!

**Comment by raviqqe** [comment]
Closed by [raviqqe/muffet](https://github.com/raviqqe/muffet).

**Comment by fd0** [comment]
Awesome!
